### ISSUE TITLE
provision_sso not configure http route for SSO as expect

### ISSUE THREAD

**Issue by holodragon** [jbossdemocentral/openbanking-workshop#2]
## Objectives:
To install openbanking workshop on integrately, sso provision need to be able to configure existing sso correctly.

## Problem:
Because the "configure_only" variable in[ main ansible playbook](https://github.com/jbossdemocentral/openbanking-workshop/blob/master/support/install/ansible/playbooks/openshift/integreatly-install.yml) is set as true, and  in the ansible role of [provision_sso](https://github.com/jbossdemocentral/openbanking-workshop/blob/master/support/install/ansible/playbooks/openshift/roles/provision_sso/tasks/main.yml) all tasks require "configure_only" set as "false"

**Comment by hguerrero** [comment]
updated to latest integreatly and 3scale so no need to use http anymore. please try and if still failing please reopen the issue.
